package com.doc.entity.product;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "product_milestone_map")
@Getter
@Setter
@NoArgsConstructor
public class ProductMilestoneMap {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "milestone_id", nullable = false)
    private Milestone milestone;

    @Column(name = "step_order", nullable = false)
    private int order; // 1 = First, 2 = Second, etc.

    @Column(name = "tat_override")
    private Integer customTatInDays; // Optional override for milestone TAT

    @Column(name = "is_mandatory", nullable = false)
    private boolean isMandatory = true; // Whether the milestone is required

    @Column(name = "payment_percentage", nullable = false)
    private double paymentPercentage; // Percentage of total payment to unlock milestone

    @Column(name = "status", nullable = false)
    private String status = "LOCKED"; // LOCKED, UNLOCKED, IN_PROGRESS, COMPLETED

    @Column(name = "is_auto_generated", nullable = false)
    private boolean isAutoGenerated = false; // True for auto-generated milestones (e.g., Certification)
}