package com.doc.notification;

public enum NotificationEventType {

    LEAD_CREATED,
    LEAD_ASSIGNED,
    LEAD_UPDATED,
    LEAD_STATUS_CHANGED,

    PROPOSAL_CREATED,
    PROPOSAL_SENT,
    PROPOSAL_APPROVED,
    PROPOSAL_REJECTED,

    PAYMENT_REGISTERED,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,

    COMPANY_APPROVAL_REQUIRED,
    COMPANY_APPROVED,
    COMPANY_REJECTED,

    PROJECT_CREATED,
    PROJECT_ASSIGNED,
    PROJECT_REASSIGNED,

    MILESTONE_ASSIGNED,
    MILESTONE_REASSIGNED,
    MILESTONE_STATUS_CHANGED,

    TASK_DUE_SOON,

    SYSTEM_NOTIFICATION
}