package com.doc.dto.productMilestoneMap;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.util.Date;

/**
 * Response DTO for product milestone mapping.
 */
@Getter
@Setter
@NoArgsConstructor
public class ProductMilestoneMapResponseDto {

    private Long id;

    private Long productId;
    private String productName;

    private Long milestoneId;
    private String milestoneName;

    private int order;

    // Execution TAT
    private boolean executionTatApplicable;
    private Integer executionTatMinutes;

    // Department TAT
    private boolean departmentTatApplicable;
    private Integer departmentTatMinutes;

    // Performance TAT
    private boolean performanceTatApplicable;
    private Integer performanceTatMinutes;

    // Customer / Project SLA TAT
    private boolean customerTatApplicable;
    private Integer customerTatMinutes;

    // Rollback / Rework TAT
    private boolean rollbackTatApplicable;
    private Integer rollbackTatMinutes;

    // Workflow rules
    private boolean strictApproval;
    private boolean allowRollback;
    private int maxAttempts;
    private boolean isMandatory;
    private double paymentPercentage;
    private boolean isAutoGenerated;
    private boolean requiresPortalDetails;

    private boolean businessDaysEnabled;

    // Common fields
    private boolean isActive;
    private boolean isDeleted;
    private LocalDate date;
    private Date createdDate;
    private Date updatedDate;
}