package com.doc.dto.productMilestoneMap;

import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Request DTO for creating or updating a product milestone mapping.
 *
 * All TAT, reminder and escalation values are stored in minutes.
 */
@Getter
@Setter
@NoArgsConstructor
public class ProductMilestoneMapRequestDto {

    @NotNull(message = "Product ID cannot be null")
    @Positive(message = "Product ID must be greater than zero")
    private Long productId;

    @NotNull(message = "Milestone ID cannot be null")
    @Positive(message = "Milestone ID must be greater than zero")
    private Long milestoneId;

    @Min(value = 1, message = "Step order must be at least 1")
    private int order;

    // =====================================================================
    // EXECUTION TAT
    // =====================================================================

    private boolean executionTatApplicable = true;

    /**
     * TAT provided to the assigned employee.
     * Example: 4 hours = 240 minutes.
     */
    @Min(
            value = 0,
            message = "Execution TAT minutes cannot be negative"
    )
    private Integer executionTatMinutes;

    // =====================================================================
    // DEPARTMENT TAT
    // =====================================================================

    private boolean departmentTatApplicable = false;

    @Min(
            value = 0,
            message = "Department TAT minutes cannot be negative"
    )
    private Integer departmentTatMinutes;

    // =====================================================================
    // PERFORMANCE TAT
    // =====================================================================

    private boolean performanceTatApplicable = true;

    @Min(
            value = 0,
            message = "Performance TAT minutes cannot be negative"
    )
    private Integer performanceTatMinutes;

    // =====================================================================
    // CUSTOMER / PROJECT SLA TAT
    // =====================================================================

    private boolean customerTatApplicable = false;

    @Min(
            value = 0,
            message = "Customer TAT minutes cannot be negative"
    )
    private Integer customerTatMinutes;

    // =====================================================================
    // ROLLBACK / REWORK TAT
    // =====================================================================

    private boolean rollbackTatApplicable = false;

    @Min(
            value = 0,
            message = "Rollback TAT minutes cannot be negative"
    )
    private Integer rollbackTatMinutes;

    // =====================================================================
    // WORKFLOW RULES
    // =====================================================================

    private boolean strictApproval = false;

    private boolean allowRollback = false;

    @Min(value = 1, message = "Max attempts must be at least 1")
    private int maxAttempts = 1;

    private boolean isMandatory = true;

    @DecimalMin(
            value = "0.0",
            message = "Payment percentage cannot be negative"
    )
    @DecimalMax(
            value = "100.0",
            message = "Single milestone payment percentage cannot exceed 100%"
    )
    private double paymentPercentage;

    private boolean isAutoGenerated = false;

    private boolean requiresPortalDetails = false;

    private boolean allowTatResetOnReassign = true;

    private boolean businessDaysEnabled = false;

    // =====================================================================
    // REMINDER / ESCALATION
    // =====================================================================

    /**
     * Example: send reminder one hour before due time = 60 minutes.
     */
    @Min(
            value = 0,
            message = "Reminder before due minutes cannot be negative"
    )
    private Integer reminderBeforeDueMinutes;

    /**
     * Example: escalate 30 minutes after due time = 30 minutes.
     */
    @Min(
            value = 0,
            message = "Manager escalation after due minutes cannot be negative"
    )
    private Integer managerEscalationAfterDueMinutes;

    @Min(
            value = 0,
            message = "HOD escalation after due minutes cannot be negative"
    )
    private Integer hodEscalationAfterDueMinutes;

    private boolean isActive = true;


}