package com.doc.dto.productMilestoneMap;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * DTO for returning ProductMilestoneMap data.
 */
@Getter
@Setter
@NoArgsConstructor
public class ProductMilestoneMapResponseDto {

    private Long id;
    private Long productId;
    private Long milestoneId;
    private String milestoneName;
    private int order;
    private double tatInDays;
    private Double rollbackTatInDays;
    private boolean strictApproval;
    private boolean allowRollback;
    private int maxAttempts;
    private boolean isMandatory;
    private double paymentPercentage;
    private String status;
    private boolean isAutoGenerated;
}