package com.doc.dto.productMilestoneMap;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * DTO for creating or updating a ProductMilestoneMap.
 */
@Getter
@Setter
@NoArgsConstructor
public class ProductMilestoneMapRequestDto {

    @NotNull(message = "Product ID cannot be null")
    private Long productId;

    @NotNull(message = "Milestone ID cannot be null")
    private Long milestoneId;

    @Min(value = 1, message = "Step order must be at least 1")
    private int order;

    @Min(value = 0, message = "TAT in days cannot be negative")
    private double tatInDays;

    @Min(value = 0, message = "Rollback TAT in days cannot be negative")
    private Double rollbackTatInDays;

    private boolean strictApproval = false;

    private boolean allowRollback = false;

    @Min(value = 0, message = "Max attempts cannot be negative")
    private int maxAttempts = 1;

    private boolean isMandatory = true;

    @Min(value = 0, message = "Payment percentage cannot be negative")
    private double paymentPercentage;

    private boolean isAutoGenerated = false;
}