package com.doc.impl;

import com.doc.dto.DepartmentAutoConfigDto;
import com.doc.entity.department.Department;
import com.doc.entity.department.DepartmentAutoConfig;
import com.doc.entity.product.ProductMilestoneMap;
import com.doc.entity.project.*;
import com.doc.entity.user.User;
import com.doc.entity.user.UserLoginStatus;
import com.doc.entity.user.UserProductMap;
import com.doc.exception.ResourceNotFoundException;
import com.doc.exception.ValidationException;
import com.doc.repository.*;
import com.doc.repository.department.DepartmentAutoConfigRepository;
import com.doc.service.AutoAssignmentService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Service implementation for automatic assignment of users to project milestones.
 */
@Service
@Transactional
public class AutoAssignmentServiceImpl implements AutoAssignmentService {

    private static final Logger logger = LoggerFactory.getLogger(AutoAssignmentServiceImpl.class);

    @Autowired
    private DepartmentAutoConfigRepository departmentAutoConfigRepository; // Repository for department auto-configurations
    @Autowired
    private UserRepository userRepository; // Repository for user data
    @Autowired
    private UserProductMapRepository userProductMapRepository; // Repository for user-product mappings
    @Autowired
    private UserPerformanceCountRepository userPerformanceCountRepository; // Repository for user performance counts
    @Autowired
    private UserLoginStatusRepository userLoginStatusRepository; // Repository for user login status
    @Autowired
    private DepartmentRepository departmentRepository; // Repository for department data
    @Autowired
    private ProjectAssignmentHistoryRepository projectAssignmentHistoryRepository; // Repository for assignment history
    @Autowired
    private ProjectRepository projectRepository; // Repository for project data
    @Autowired
    private ProjectMilestoneAssignmentRepository projectMilestoneAssignmentRepository; // Repository for milestone assignments
    @Autowired
    private MilestoneStatusRepository milestoneStatusRepository; // Repository for milestone statuses

    /**
     * Assigns a user to a milestone based on department configuration, company alignment, and availability.
     * @param milestone The milestone to assign a user to.
     * @param updatedById The ID of the user updating the assignment.
     * @return AssignmentResult containing the assigned user and reason, or null if no assignment is made.
     */
    @Override
    public AssignmentResult assignMilestoneUser(ProductMilestoneMap milestone, Long updatedById) {
        logger.info("Starting user assignment for milestone: {}, product ID: {}, updated by user ID: {}",
                milestone.getMilestone().getName(), milestone.getProduct().getId(), updatedById);

        // Check if the milestone is mandatory
        if (!milestone.isMandatory()) {
            logger.debug("Milestone {} is not mandatory, skipping assignment", milestone.getMilestone().getName());
            return new AssignmentResult(null, "Skipped non-mandatory milestone");
        }

        // Check if the milestone is auto-generated (no user assignment needed)
        if (milestone.isAutoGenerated()) {
            logger.debug("Milestone {} is auto-generated, no assignment needed", milestone.getMilestone().getName());
            return null;
        }

        // Retrieve departments associated with the milestone
        List<Department> departments = milestone.getMilestone().getDepartments();
        logger.debug("Found {} departments for milestone {}", departments.size(), milestone.getMilestone().getName());

        // Handle case where no departments are mapped (queue for manual assignment)
        if (departments.isEmpty()) {
            logger.warn("No departments mapped for milestone {}, queuing for manual assignment", milestone.getMilestone().getName());
            queueMilestone(milestone, updatedById);
            return new AssignmentResult(null, "Queued due to no department mapping");
        }

        // Use the first department (assumes single department per milestone)
        Department dept = departments.get(0);
        logger.debug("Selected department: {} (ID: {}) for milestone assignment", dept.getName(), dept.getId());

        // Load department auto-configuration, create default if not found
        DepartmentAutoConfig config = departmentAutoConfigRepository.findByDepartmentIdAndIsDeletedFalse(dept.getId())
                .orElseGet(() -> {
                    logger.info("No auto-config found for department ID {}, creating default config", dept.getId());
                    DepartmentAutoConfig newConfig = new DepartmentAutoConfig();
                    newConfig.setDepartment(dept);
                    newConfig.setAutoAssignmentEnabled(false);
                    return newConfig;
                });
        logger.debug("Department auto-config: enabled={}, manualOnly={}, alignment={}, availability={}, rating={}",
                config.isAutoAssignmentEnabled(), config.isManualOnly(), config.isCompanyAlignmentEnabled(),
                config.isAvailabilityRequired(), config.isRatingPrioritizationEnabled());

        // Check if auto-assignment is disabled
        if (!config.isAutoAssignmentEnabled()) {
            logger.info("Auto-assignment disabled for department {}, pending manual assignment", dept.getName());
            return new AssignmentResult(null, "Pending manual assignment");
        }

        // Check if manual-only mode is enabled
        if (config.isManualOnly()) {
            logger.info("Manual-only mode enabled for department {}, pending manual assignment", dept.getName());
            return new AssignmentResult(null, "Pending manual assignment due to manual-only mode");
        }

        // Fetch project details for company and contact information
        Project project = projectRepository.findByProductIdAndMilestoneId(milestone.getProduct().getId(), milestone.getMilestone().getId())
                .orElseThrow(() -> {
                    logger.error("Project not found for milestone {}, product ID {}", milestone.getMilestone().getName(), milestone.getProduct().getId());
                    return new ResourceNotFoundException("Project not found for milestone", "ERR_PROJECT_NOT_FOUND");
                });
        logger.debug("Found project: {} (ID: {}) for milestone assignment", project.getProjectNo(), project.getId());

        // Retrieve active users in the department
        List<User> deptUsers = userRepository.findByDepartmentsIdAndIsActiveTrueAndIsDeletedFalse(dept.getId());
        logger.debug("Found {} active users in department {}", deptUsers.size(), dept.getName());
        if (deptUsers.isEmpty()) {
            logger.warn("No active users in department {}, falling back to manager", dept.getName());
            return assignFallbackManager(milestone, dept, updatedById);
        }

        // Fetch user-product mappings for the product
        List<UserProductMap> mappings = userProductMapRepository.findByProductIdAndIsDeletedFalse(milestone.getProduct().getId());
        logger.debug("Found {} user-product mappings for product ID {}", mappings.size(), milestone.getProduct().getId());

        // Filter eligible users based on department, rating, and availability
        List<UserProductMap> eligibleMappings = mappings.stream()
                .filter(m -> deptUsers.stream().anyMatch(u -> u.getId().equals(m.getUser().getId())))
                .filter(m -> config.isRatingPrioritizationEnabled() ? m.getRating() != null && m.getRating() > 0 : true)
                .filter(m -> config.isAvailabilityRequired() ? isUserAvailable(m.getUser(), milestone.getProduct().getId()) : true)
                .collect(Collectors.toList());
        logger.debug("Filtered to {} eligible user-product mappings", eligibleMappings.size());

        // If no eligible users, fall back to manager
        if (eligibleMappings.isEmpty()) {
            logger.warn("No eligible users found for milestone {}, falling back to manager", milestone.getMilestone().getName());
            return assignFallbackManager(milestone, dept, updatedById);
        }

        // Apply company alignment if enabled
        if (config.isCompanyAlignmentEnabled()) {
            logger.debug("Applying company alignment for milestone {}", milestone.getMilestone().getName());
            Optional<UserProductMap> alignedUser = findAlignedUser(project, milestone, dept, eligibleMappings);
            if (alignedUser.isPresent()) {
                logger.info("Assigning milestone {} to aligned user ID: {}", milestone.getMilestone().getName(), alignedUser.get().getUser().getId());
                return assignUser(alignedUser.get(), "Assigned based on company alignment", updatedById);
            }
            logger.debug("No aligned user found, proceeding to round-robin");
        }

        // Apply rating-based prioritization with round-robin if enabled
        if (config.isRatingPrioritizationEnabled()) {
            logger.debug("Applying rating-based round-robin for milestone {}", milestone.getMilestone().getName());
            Map<Double, List<UserProductMap>> ratingGroups = eligibleMappings.stream()
                    .collect(Collectors.groupingBy(UserProductMap::getRating));
            List<Double> tiers = new ArrayList<>(ratingGroups.keySet());
            tiers.sort(Comparator.reverseOrder());
            logger.debug("Found {} rating tiers: {}", tiers.size(), tiers);

            for (Double tier : tiers) {
                List<UserProductMap> tierMappings = ratingGroups.get(tier);
                Optional<UserProductMap> selected = selectRoundRobin(tierMappings, milestone.getProduct().getId());
                if (selected.isPresent()) {
                    logger.info("Assigning milestone {} to user ID: {} with rating {}", milestone.getMilestone().getName(),
                            selected.get().getUser().getId(), tier);
                    return assignUser(selected.get(), "Assigned based on " + tier + "-star rating and round-robin", updatedById);
                }
                logger.debug("No available users in rating tier {}", tier);
            }
        } else {
            // Apply pure round-robin
            logger.debug("Applying pure round-robin for milestone {}", milestone.getMilestone().getName());
            Optional<UserProductMap> selected = selectRoundRobin(eligibleMappings, milestone.getProduct().getId());
            if (selected.isPresent()) {
                logger.info("Assigning milestone {} to user ID: {} via pure round-robin", milestone.getMilestone().getName(),
                        selected.get().getUser().getId());
                return assignUser(selected.get(), "Assigned based on pure round-robin", updatedById);
            }
            logger.debug("No available users in round-robin selection");
        }

        // Fall back to manager if no user is selected
        logger.warn("No user selected for milestone {}, falling back to manager", milestone.getMilestone().getName());
        return assignFallbackManager(milestone, dept, updatedById);
    }

    /**
     * Queues a milestone for manual assignment when no departments are mapped.
     * @param milestone The milestone to queue.
     * @param updatedById The ID of the user updating the assignment.
     */
    private void queueMilestone(ProductMilestoneMap milestone, Long updatedById) {
        logger.info("Queuing milestone {} for manual assignment due to no department mapping", milestone.getMilestone().getName());

        // Fetch the project associated with the milestone
        Project project = projectRepository.findByProductIdAndMilestoneId(milestone.getProduct().getId(), milestone.getMilestone().getId())
                .orElseThrow(() -> {
                    logger.error("Project not found for milestone {}, product ID {}", milestone.getMilestone().getName(), milestone.getProduct().getId());
                    return new ResourceNotFoundException("Project not found for milestone", "ERR_PROJECT_NOT_FOUND");
                });
        logger.debug("Found project: {} (ID: {}) for queuing milestone", project.getProjectNo(), project.getId());

        // Fetch the milestone assignment
        ProjectMilestoneAssignment assignment = projectMilestoneAssignmentRepository
                .findByProjectIdAndMilestoneIdAndIsDeletedFalse(project.getId(), milestone.getMilestone().getId())
                .orElseThrow(() -> {
                    logger.error("Assignment not found for project ID {}, milestone ID {}", project.getId(), milestone.getMilestone().getId());
                    return new ResourceNotFoundException("Assignment not found", "ERR_ASSIGNMENT_NOT_FOUND");
                });
        logger.debug("Found milestone assignment ID: {} for queuing", assignment.getId());

        // Set the assignment status to QUEUED
        MilestoneStatus queuedStatus = milestoneStatusRepository.findByName("QUEUED")
                .orElseThrow(() -> {
                    logger.error("QUEUED status not found in milestone_status table");
                    return new ResourceNotFoundException("QUEUED status not found", "ERR_STATUS_NOT_FOUND");
                });
        assignment.setStatus(queuedStatus);
        assignment.setStatusReason("Queued due to no department mapping");
        assignment.setUpdatedBy(updatedById);
        assignment.setUpdatedDate(new Date());
        projectMilestoneAssignmentRepository.save(assignment);
        logger.info("Milestone assignment ID {} set to QUEUED status", assignment.getId());

        // Log the queuing action to assignment history
        ProjectAssignmentHistory history = new ProjectAssignmentHistory();
        history.setProject(project);
        history.setMilestoneAssignment(assignment);
        history.setAssignedUser(null);
        history.setAssignmentReason("Queued due to no department mapping");
        history.setCreatedDate(new Date());
        history.setUpdatedDate(new Date());
        history.setCreatedBy(updatedById);
        history.setUpdatedBy(updatedById);
        history.setDeleted(false);
        projectAssignmentHistoryRepository.save(history);
        logger.info("Logged queuing action to assignment history for milestone {}", milestone.getMilestone().getName());

        // Notify Operation Head (placeholder for notification service)
        logger.info("Notifying Operation Head for queued milestone: {}", milestone.getMilestone().getName());
        // Example: notificationService.notifyOperationHead("Milestone " + milestone.getMilestone().getName() + " queued for manual assignment");
    }

    /**
     * Finds a user previously assigned to the same company or contact for continuity.
     * @param project The project containing company and contact details.
     * @param milestone The milestone being assigned.
     * @param dept The department handling the milestone.
     * @param eligibleMappings List of eligible user-product mappings.
     * @return Optional containing the aligned user mapping, or empty if none found.
     */
    private Optional<UserProductMap> findAlignedUser(Project project, ProductMilestoneMap milestone, Department dept,
                                                     List<UserProductMap> eligibleMappings) {
        logger.debug("Checking company alignment for project ID {}, milestone {}, department {}",
                project.getId(), milestone.getMilestone().getName(), dept.getName());

        // Fetch prior assignments for the same company and milestone in this department
        List<ProjectAssignmentHistory> history = projectAssignmentHistoryRepository.findByProjectCompanyIdAndMilestoneIdAndDepartmentId(
                project.getCompany().getId(), milestone.getMilestone().getId(), dept.getId());
        logger.debug("Found {} prior assignments for company ID {}", history.size(), project.getCompany().getId());

        // Sort by most recent
        Optional<ProjectAssignmentHistory> recentAssignment = history.stream()
                .filter(h -> h.getAssignedUser() != null)
                .max(Comparator.comparing(ProjectAssignmentHistory::getCreatedDate));

        if (recentAssignment.isPresent()) {
            User alignedUser = recentAssignment.get().getAssignedUser();
            logger.debug("Found recent assignment to user ID: {} for company ID {}", alignedUser.getId(), project.getCompany().getId());
            // Check if aligned user is in eligible mappings
            Optional<UserProductMap> alignedMapping = eligibleMappings.stream()
                    .filter(m -> m.getUser().getId().equals(alignedUser.getId()))
                    .findFirst();
            if (alignedMapping.isPresent()) {
                logger.info("Aligned user {} (ID: {}) selected for company ID {}",
                        alignedUser.getFullName(), alignedUser.getId(), project.getCompany().getId());
                return alignedMapping;
            }
            logger.debug("Aligned user ID {} not eligible for current milestone", alignedUser.getId());
        }

        // Fallback to contact-based matching (email/phone)
        if (project.getContact() != null) {
            String email = project.getContact().getEmails();
            String phone = project.getContact().getContactNo();
            logger.debug("Checking contact-based alignment with email: {}, phone: {}", email, phone);
            history = projectAssignmentHistoryRepository.findByContactDetails(email, phone, milestone.getMilestone().getId(), dept.getId());
            recentAssignment = history.stream()
                    .filter(h -> h.getAssignedUser() != null)
                    .max(Comparator.comparing(ProjectAssignmentHistory::getCreatedDate));
            if (recentAssignment.isPresent()) {
                User alignedUser = recentAssignment.get().getAssignedUser();
                logger.debug("Found recent contact-based assignment to user ID: {}", alignedUser.getId());
                Optional<UserProductMap> alignedMapping = eligibleMappings.stream()
                        .filter(m -> m.getUser().getId().equals(alignedUser.getId()))
                        .findFirst();
                if (alignedMapping.isPresent()) {
                    logger.info("Aligned user {} (ID: {}) selected via contact details for company ID {}",
                            alignedUser.getFullName(), alignedUser.getId(), project.getCompany().getId());
                    return alignedMapping;
                }
                logger.debug("Contact-aligned user ID {} not eligible for current milestone", alignedUser.getId());
            }
        }

        logger.debug("No aligned user found for milestone {}", milestone.getMilestone().getName());
        return Optional.empty();
    }

    /**
     * Checks if a user is available based on login status and bucket size.
     * @param user The user to check.
     * @param productId The product ID for bucket size checking.
     * @return True if the user is available, false otherwise.
     */
    private boolean isUserAvailable(User user, Long productId) {
        logger.debug("Checking availability for user ID: {}, product ID: {}", user != null ? user.getId() : null, productId);

        if (user == null || user.isDeleted() || !user.isActive()) {
            logger.debug("User is null, deleted, or inactive");
            return false;
        }

        // Check login status
        UserLoginStatus loginStatus = userLoginStatusRepository.findByUserIdAndIsDeletedFalse(user.getId()).orElse(null);
        if (loginStatus == null) {
            logger.debug("No login status found for user ID {}", user.getId());
            return false;
        }

        LocalDate today = LocalDate.now();
        boolean isAvailable = loginStatus.isOnline() ||
                (loginStatus.getLastOnline() != null &&
                        loginStatus.getLastOnline().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().equals(today));
        logger.debug("User ID {} online status: {}, last online: {}", user.getId(), loginStatus.isOnline(), loginStatus.getLastOnline());

        // Check bucket size
        UserPerformanceCount count = userPerformanceCountRepository.findByUserIdAndProductId(user.getId(), productId);
        int maxProjects = user.getBucketSize();
        boolean bucketOk = count == null || count.getAssignmentCount() < maxProjects;
        logger.debug("User ID {} bucket check: assignment count={}, max projects={}", user.getId(),
                count != null ? count.getAssignmentCount() : 0, maxProjects);

        boolean available = isAvailable && bucketOk;
        logger.debug("User ID {} availability result: {}", user.getId(), available);
        return available;
    }

    /**
     * Selects a user using round-robin logic, considering bucket size.
     * @param mappings List of user-product mappings to select from.
     * @param productId The product ID for bucket size checking.
     * @return Optional containing the selected user mapping, or empty if none available.
     */
    private Optional<UserProductMap> selectRoundRobin(List<UserProductMap> mappings, Long productId) {
        logger.debug("Applying round-robin selection for {} mappings, product ID: {}", mappings.size(), productId);
        if (mappings.isEmpty()) {
            logger.debug("No mappings provided for round-robin selection");
            return Optional.empty();
        }

        // Reset isAssigned flag if all users are assigned
        boolean allAssigned = mappings.stream().allMatch(UserProductMap::isAssigned);
        if (allAssigned) {
            logger.info("All mappings assigned, resetting isAssigned flags");
            mappings.forEach(m -> {
                m.setAssigned(false);
                userProductMapRepository.save(m);
                logger.debug("Reset isAssigned for user ID: {}", m.getUser().getId());
            });
        }

        // Select the first available user with bucket space
        Optional<UserProductMap> selected = mappings.stream()
                .filter(m -> !m.isAssigned())
                .filter(m -> {
                    UserPerformanceCount count = userPerformanceCountRepository.findByUserIdAndProductId(m.getUser().getId(), productId);
                    int maxProjects = m.getUser().getBucketSize();
                    boolean available = count == null || count.getAssignmentCount() < maxProjects;
                    logger.debug("Round-robin check for user ID {}: available={}", m.getUser().getId(), available);
                    return available;
                })
                .findFirst();

        if (selected.isPresent()) {
            logger.info("Selected user ID {} via round-robin", selected.get().getUser().getId());
        } else {
            logger.debug("No available users found in round-robin selection");
        }
        return selected;
    }

    /**
     * Assigns a user to a milestone and updates performance counts.
     * @param mapping The user-product mapping to assign.
     * @param reason The reason for the assignment.
     * @param updatedById The ID of the user updating the assignment.
     * @return AssignmentResult containing the assigned user and reason.
     */
    private AssignmentResult assignUser(UserProductMap mapping, String reason, Long updatedById) {
        logger.info("Assigning user ID {} to milestone with reason: {}", mapping.getUser().getId(), reason);
        User user = mapping.getUser();

        // Mark the mapping as assigned
        mapping.setAssigned(true);
        userProductMapRepository.save(mapping);
        logger.debug("Marked user-product mapping as assigned for user ID {}, product ID {}", user.getId(), mapping.getProduct().getId());

        // Update or create user performance count
        UserPerformanceCount count = userPerformanceCountRepository.findByUserIdAndProductId(user.getId(), mapping.getProduct().getId());
        if (count == null) {
            count = new UserPerformanceCount();
            count.setUser(user);
            count.setProduct(mapping.getProduct());
            count.setAssignmentCount(1);
            count.setTimeSpent(0.0);
            count.setLastUpdatedDate(new Date());
            count.setCreatedDate(new Date());
            count.setUpdatedDate(new Date());
            count.setCreatedBy(updatedById);
            count.setUpdatedBy(updatedById);
            count.setDeleted(false);
            logger.debug("Created new performance count for user ID {}, product ID {}", user.getId(), mapping.getProduct().getId());
        } else {
            count.setAssignmentCount(count.getAssignmentCount() + 1);
            count.setLastUpdatedDate(new Date());
            count.setUpdatedDate(new Date());
            count.setUpdatedBy(updatedById);
            logger.debug("Incremented assignment count to {} for user ID {}, product ID {}",
                    count.getAssignmentCount(), user.getId(), mapping.getProduct().getId());
        }
        userPerformanceCountRepository.save(count);
        logger.info("Saved performance count for user ID {}", user.getId());

        return new AssignmentResult(user, reason);
    }

    /**
     * Assigns the milestone to a department manager or Operation Head if no users are available.
     * @param milestone The milestone to assign.
     * @param department The department handling the milestone.
     * @param updatedById The ID of the user updating the assignment.
     * @return AssignmentResult containing the assigned user (manager/Operation Head) or null for manual assignment.
     */
    private AssignmentResult assignFallbackManager(ProductMilestoneMap milestone, Department department, Long updatedById) {
        logger.info("Falling back to manager for milestone {}, department {}", milestone.getMilestone().getName(), department.getName());

        // Try assigning to department manager
        Optional<User> manager = userRepository.findManagerByDepartmentId(department.getId())
                .stream()
                .filter(u -> isUserAvailable(u, milestone.getProduct().getId()))
                .findFirst();

        if (manager.isPresent()) {
            logger.debug("Found available manager ID {} for department {}", manager.get().getId(), department.getName());
            UserProductMap managerMap = userProductMapRepository.findByUserIdAndProductIdAndIsDeletedFalse(manager.get().getId(), milestone.getProduct().getId())
                    .orElseGet(() -> {
                        logger.info("No user-product mapping for manager ID {}, creating new mapping", manager.get().getId());
                        UserProductMap newMap = new UserProductMap();
                        newMap.setUser(manager.get());
                        newMap.setProduct(milestone.getProduct());
                        newMap.setRating(0.0);
                        newMap.setAssigned(false);
                        newMap.setDeleted(false);
                        newMap.setCreatedDate(new Date());
                        newMap.setUpdatedDate(new Date());
                        newMap.setCreatedBy(updatedById);
                        newMap.setUpdatedBy(updatedById);
                        return newMap;
                    });
            return assignUser(managerMap, "Assigned to manager due to no available users", updatedById);
        }

        // Fallback to Operation Head if manager is unavailable
        logger.info("No available manager for department {}, assigning to OPERATION_HEAD", department.getName());
        Optional<User> operationHead = userRepository.findAdmins()
                .stream()
                .filter(u -> isUserAvailable(u, milestone.getProduct().getId()))
                .findFirst();

        if (operationHead.isPresent()) {
            logger.debug("Found available Operation Head ID {}", operationHead.get().getId());
            UserProductMap operationHeadMap = userProductMapRepository
                    .findByUserIdAndProductIdAndIsDeletedFalse(operationHead.get().getId(), milestone.getProduct().getId())
                    .orElseGet(() -> {
                        logger.info("No user-product mapping for Operation Head ID {}, creating new mapping", operationHead.get().getId());
                        UserProductMap newMap = new UserProductMap();
                        newMap.setUser(operationHead.get());
                        newMap.setProduct(milestone.getProduct());
                        newMap.setRating(0.0);
                        newMap.setAssigned(false);
                        newMap.setDeleted(false);
                        newMap.setCreatedDate(new Date());
                        newMap.setUpdatedDate(new Date());
                        newMap.setCreatedBy(updatedById);
                        newMap.setUpdatedBy(updatedById);
                        return newMap;
                    });
            return assignUser(operationHeadMap, "Assigned to Operation Head due to no available manager or users", updatedById);
        }

        // If no Operation Head is available, fall back to manual assignment
        logger.warn("No available Operation Head for department {}, pending manual assignment", department.getName());
        return new AssignmentResult(null, "Pending manual assignment due to no available Operation Head or manager");
    }

    /**
     * Updates the auto-assignment configuration for a department.
     * @param dto The configuration data to apply.
     */
    @Override
    public void updateDepartmentAutoConfig(DepartmentAutoConfigDto dto) {
        logger.info("Updating auto-config for department ID: {}, name: {}", dto.getDepartmentId(), dto.getDepartmentName());

        // Validate configuration combinations
        if (dto.isRatingPrioritizationEnabled() && !dto.isAvailabilityRequired() && !dto.getDepartmentName().equalsIgnoreCase("LEGAL")) {
            logger.error("Invalid config: Rating prioritization without availability for non-LEGAL department {}", dto.getDepartmentName());
            throw new ValidationException("Rating prioritization requires availability check unless department is LEGAL",
                    "INVALID_CONFIG_COMBINATION");
        }
        if (dto.isManualOnly() && (dto.isCompanyAlignmentEnabled() || dto.isAvailabilityRequired() || dto.isRatingPrioritizationEnabled())) {
            logger.error("Invalid config: Manual-only mode combined with other features for department {}", dto.getDepartmentName());
            throw new ValidationException("Manual-only mode cannot be combined with other auto-assignment features",
                    "INVALID_MANUAL_ONLY_COMBINATION");
        }

        // Fetch department
        Department department = departmentRepository.findByIdAndIsDeletedFalse(dto.getDepartmentId())
                .orElseThrow(() -> {
                    logger.error("Department ID {} not found", dto.getDepartmentId());
                    return new ResourceNotFoundException("Department not found", "ERR_DEPARTMENT_NOT_FOUND");
                });
        logger.debug("Found department: {} (ID: {})", department.getName(), department.getId());

        // Load or create auto-config
        DepartmentAutoConfig config = departmentAutoConfigRepository.findByDepartmentIdAndIsDeletedFalse(department.getId())
                .orElseGet(() -> {
                    logger.info("No auto-config found for department {}, creating new config", department.getName());
                    DepartmentAutoConfig newConfig = new DepartmentAutoConfig();
                    newConfig.setDepartment(department);
                    newConfig.setCreatedDate(new Date());
                    return newConfig;
                });

        // Update configuration fields
        config.setAutoAssignmentEnabled(dto.isAutoAssignmentEnabled());
        config.setAvailabilityRequired(dto.isAvailabilityRequired());
        config.setRatingPrioritizationEnabled(dto.isRatingPrioritizationEnabled());
        config.setCompanyAlignmentEnabled(dto.isCompanyAlignmentEnabled());
        config.setManualOnly(dto.isManualOnly());
        config.setUpdatedDate(new Date());
        logger.debug("Updated auto-config: enabled={}, manualOnly={}, alignment={}, availability={}, rating={}",
                config.isAutoAssignmentEnabled(), config.isManualOnly(), config.isCompanyAlignmentEnabled(),
                config.isAvailabilityRequired(), config.isRatingPrioritizationEnabled());

        // Save configuration
        departmentAutoConfigRepository.save(config);
        logger.info("Auto-config updated successfully for department: {}", department.getName());
    }
}