package com.doc.impl;

import com.doc.dto.DepartmentAutoConfigDto;
import com.doc.entity.department.Department;
import com.doc.entity.department.DepartmentAutoConfig;
import com.doc.entity.product.ProductMilestoneMap;
import com.doc.entity.project.*;
import com.doc.entity.user.User;
import com.doc.entity.user.UserLoginStatus;
import com.doc.entity.user.UserProductMap;
import com.doc.exception.ResourceNotFoundException;
import com.doc.exception.ValidationException;
import com.doc.repository.*;
import com.doc.repository.department.DepartmentAutoConfigRepository;
import com.doc.service.AutoAssignmentService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Service implementation for automatic assignment of users to project milestones.
 */
@Service
@Transactional
public class AutoAssignmentServiceImpl implements AutoAssignmentService {

    private static final Logger logger = LoggerFactory.getLogger(AutoAssignmentServiceImpl.class);

    @Autowired
    private DepartmentAutoConfigRepository departmentAutoConfigRepository;
    @Autowired
    private UserRepository userRepository;
    @Autowired
    private UserProductMapRepository userProductMapRepository;
    @Autowired
    private UserPerformanceCountRepository userPerformanceCountRepository;
    @Autowired
    private UserLoginStatusRepository userLoginStatusRepository;
    @Autowired
    private DepartmentRepository departmentRepository;
    @Autowired
    private ProjectAssignmentHistoryRepository projectAssignmentHistoryRepository;
    @Autowired
    private ProjectRepository projectRepository;
    @Autowired
    private ProjectMilestoneAssignmentRepository projectMilestoneAssignmentRepository;
    @Autowired
    private MilestoneStatusRepository milestoneStatusRepository;

    @Override
    public AssignmentResult assignMilestoneUser(ProductMilestoneMap milestone, Long updatedById) {
        logger.info("Starting user assignment for milestone: {}, product ID: {}, updated by user ID: {}",
                milestone.getMilestone().getName(), milestone.getProduct().getId(), updatedById);

        if (!milestone.isMandatory()) {
            logger.debug("Milestone {} is not mandatory, skipping assignment", milestone.getMilestone().getName());
            return new AssignmentResult(null, "Skipped non-mandatory milestone");
        }

        if (milestone.isAutoGenerated()) {
            logger.debug("Milestone {} is auto-generated, no assignment needed", milestone.getMilestone().getName());
            return null;
        }

        List<Department> departments = milestone.getMilestone().getDepartments();
        logger.debug("Found {} departments for milestone {}", departments.size(), milestone.getMilestone().getName());

        if (departments.isEmpty()) {
            logger.warn("No departments mapped for milestone {}, queuing for manual assignment", milestone.getMilestone().getName());
            queueMilestone(milestone, updatedById);
            return new AssignmentResult(null, "Queued due to no department mapping");
        }

        Department dept = departments.get(0);
        logger.debug("Selected department: {} (ID: {}) for milestone assignment", dept.getName(), dept.getId());

        DepartmentAutoConfig config = departmentAutoConfigRepository.findByDepartmentIdAndIsDeletedFalse(dept.getId())
                .orElseGet(() -> {
                    logger.info("No auto-config found for department ID {}, creating default config", dept.getId());
                    DepartmentAutoConfig newConfig = new DepartmentAutoConfig();
                    newConfig.setDepartment(dept);
                    newConfig.setAutoAssignmentEnabled(false);
                    newConfig.setRoundRobinEnabled(true);
                    return newConfig;
                });

        logger.debug("Department auto-config: enabled={}, manualOnly={}, alignment={}, availability={}, rating={}, roundRobin={}",
                config.isAutoAssignmentEnabled(), config.isManualOnly(), config.isCompanyAlignmentEnabled(),
                config.isAvailabilityRequired(), config.isRatingPrioritizationEnabled(), config.isRoundRobinEnabled());

        if (!config.isAutoAssignmentEnabled()) {
            logger.info("Auto-assignment disabled for department {}, pending manual assignment", dept.getName());
            return new AssignmentResult(null, "Pending manual assignment");
        }

        if (config.isManualOnly()) {
            logger.info("Manual-only mode enabled for department {}, pending manual assignment", dept.getName());
            return new AssignmentResult(null, "Pending manual assignment due to manual-only mode");
        }

        Project project = projectRepository.findByProductIdAndMilestoneId(milestone.getProduct().getId(), milestone.getMilestone().getId())
                .orElseThrow(() -> {
                    logger.error("Project not found for milestone {}, product ID {}", milestone.getMilestone().getName(), milestone.getProduct().getId());
                    return new ResourceNotFoundException("Project not found for milestone", "ERR_PROJECT_NOT_FOUND");
                });
        logger.debug("Found project: {} (ID: {}) for milestone assignment", project.getProjectNo(), project.getId());

        List<User> deptUsers = userRepository.findByDepartmentsIdAndIsActiveTrueAndIsDeletedFalse(dept.getId());
        logger.debug("Found {} active users in department {}", deptUsers.size(), dept.getName());
        if (deptUsers.isEmpty()) {
            logger.warn("No active users in department {}, falling back to manager", dept.getName());
            return assignFallbackManager(milestone, dept, updatedById);
        }

        List<UserProductMap> mappings = userProductMapRepository.findByProductIdAndIsDeletedFalse(milestone.getProduct().getId());
        logger.debug("Found {} user-product mappings for product ID {}", mappings.size(), milestone.getProduct().getId());

        List<UserProductMap> eligibleMappings = mappings.stream()
                .filter(m -> deptUsers.stream().anyMatch(u -> u.getId().equals(m.getUser().getId())))
                .filter(m -> config.isRatingPrioritizationEnabled() ? m.getRating() != null && m.getRating() > 0 : true)
                .filter(m -> config.isAvailabilityRequired() ? isUserAvailable(m.getUser(), milestone.getProduct().getId()) : true)
                .collect(Collectors.toList());
        logger.debug("Filtered to {} eligible user-product mappings", eligibleMappings.size());

        if (eligibleMappings.isEmpty()) {
            logger.warn("No eligible users found for milestone {}, falling back to manager", milestone.getMilestone().getName());
            return assignFallbackManager(milestone, dept, updatedById);
        }

        // Company alignment
        if (config.isCompanyAlignmentEnabled()) {
            logger.debug("Applying company alignment for milestone {}", milestone.getMilestone().getName());
            Optional<UserProductMap> alignedUser = findAlignedUser(project, milestone, dept, eligibleMappings);
            if (alignedUser.isPresent()) {
                logger.info("Assigning milestone {} to aligned user ID: {}", milestone.getMilestone().getName(), alignedUser.get().getUser().getId());
                return assignUser(alignedUser.get(), "Assigned based on company alignment", updatedById);
            }
            logger.debug("No aligned user found, proceeding to selection");
        }

        // Unified selection logic
        Optional<UserProductMap> selected;

        if (config.isRatingPrioritizationEnabled()) {
            logger.debug("Applying rating-based selection");
            Map<Double, List<UserProductMap>> ratingGroups = eligibleMappings.stream()
                    .collect(Collectors.groupingBy(UserProductMap::getRating));
            List<Double> tiers = new ArrayList<>(ratingGroups.keySet());
            tiers.sort(Comparator.reverseOrder());

            for (Double tier : tiers) {
                List<UserProductMap> tierMappings = ratingGroups.get(tier);
                if (config.isRoundRobinEnabled()) {
                    selected = selectRoundRobin(tierMappings, milestone.getProduct().getId());
                } else {
                    selected = selectBestAvailable(tierMappings, milestone.getProduct().getId());
                }
                if (selected.isPresent()) {
                    String reason = "Assigned based on " + tier + "-star rating" +
                            (config.isRoundRobinEnabled() ? " and round-robin" : " and load balancing");
                    return assignUser(selected.get(), reason, updatedById);
                }
            }
        } else {
            if (config.isRoundRobinEnabled()) {
                logger.debug("Applying pure round-robin");
                selected = selectRoundRobin(eligibleMappings, milestone.getProduct().getId());
            } else {
                logger.debug("Applying best-available (no RR)");
                selected = selectBestAvailable(eligibleMappings, milestone.getProduct().getId());
            }
            if (selected.isPresent()) {
                String reason = config.isRoundRobinEnabled() ? "Assigned based on pure round-robin"
                        : "Assigned based on load balancing";
                return assignUser(selected.get(), reason, updatedById);
            }
        }

        logger.warn("No user selected for milestone {}, falling back to manager", milestone.getMilestone().getName());
        return assignFallbackManager(milestone, dept, updatedById);
    }

    private void queueMilestone(ProductMilestoneMap milestone, Long updatedById) {
        logger.info("Queuing milestone {} for manual assignment due to no department mapping", milestone.getMilestone().getName());

        Project project = projectRepository.findByProductIdAndMilestoneId(milestone.getProduct().getId(), milestone.getMilestone().getId())
                .orElseThrow(() -> {
                    logger.error("Project not found for milestone {}, product ID {}", milestone.getMilestone().getName(), milestone.getProduct().getId());
                    return new ResourceNotFoundException("Project not found for milestone", "ERR_PROJECT_NOT_FOUND");
                });

        ProjectMilestoneAssignment assignment = projectMilestoneAssignmentRepository
                .findByProjectIdAndMilestoneIdAndIsDeletedFalse(project.getId(), milestone.getMilestone().getId())
                .orElseThrow(() -> {
                    logger.error("Assignment not found for project ID {}, milestone ID {}", project.getId(), milestone.getMilestone().getId());
                    return new ResourceNotFoundException("Assignment not found", "ERR_ASSIGNMENT_NOT_FOUND");
                });



        MilestoneStatus queuedStatus = milestoneStatusRepository.findByName("QUEUED")
                .orElseThrow(() -> {
                    logger.error("QUEUED status not found in milestone_status table");
                    return new ResourceNotFoundException("QUEUED status not found", "ERR_STATUS_NOT_FOUND");
                });

        assignment.setStatus(queuedStatus);
        assignment.setStatusReason("Queued due to no department mapping");
        assignment.setUpdatedBy(updatedById);
        assignment.setUpdatedDate(new Date());
        projectMilestoneAssignmentRepository.save(assignment);
        logger.info("Milestone assignment ID {} set to QUEUED status", assignment.getId());

        ProjectAssignmentHistory history = new ProjectAssignmentHistory();
        history.setProject(project);
        history.setMilestoneAssignment(assignment);
        history.setAssignedUser(null);
        history.setAssignmentReason("Queued due to no department mapping");
        history.setCreatedDate(new Date());
        history.setUpdatedDate(new Date());
        history.setCreatedBy(updatedById);
        history.setUpdatedBy(updatedById);
        history.setDeleted(false);
        projectAssignmentHistoryRepository.save(history);
        logger.info("Logged queuing action to assignment history for milestone {}", milestone.getMilestone().getName());
    }

    private Optional<UserProductMap> findAlignedUser(Project project, ProductMilestoneMap milestone, Department dept,
                                                     List<UserProductMap> eligibleMappings) {
        logger.debug("Checking company alignment for project ID {}, milestone {}, department {}",
                project.getId(), milestone.getMilestone().getName(), dept.getName());

        List<ProjectAssignmentHistory> history = projectAssignmentHistoryRepository.findByProjectCompanyIdAndMilestoneIdAndDepartmentId(
                project.getCompany().getId(), milestone.getMilestone().getId(), dept.getId());
        logger.debug("Found {} prior assignments for company ID {}", history.size(), project.getCompany().getId());

        Optional<ProjectAssignmentHistory> recentAssignment = history.stream()
                .filter(h -> h.getAssignedUser() != null)
                .max(Comparator.comparing(ProjectAssignmentHistory::getCreatedDate));

        if (recentAssignment.isPresent()) {
            User alignedUser = recentAssignment.get().getAssignedUser();
            Optional<UserProductMap> alignedMapping = eligibleMappings.stream()
                    .filter(m -> m.getUser().getId().equals(alignedUser.getId()))
                    .findFirst();
            if (alignedMapping.isPresent()) {
                logger.info("Aligned user {} (ID: {}) selected for company ID {}",
                        alignedUser.getFullName(), alignedUser.getId(), project.getCompany().getId());
                return alignedMapping;
            }
        }

        if (project.getContact() != null) {
            String email = project.getContact().getEmails();
            String phone = project.getContact().getContactNo();
            logger.debug("Checking contact-based alignment with email: {}, phone: {}", email, phone);
            history = projectAssignmentHistoryRepository.findByContactDetails(email, phone, milestone.getMilestone().getId(), dept.getId());
            recentAssignment = history.stream()
                    .filter(h -> h.getAssignedUser() != null)
                    .max(Comparator.comparing(ProjectAssignmentHistory::getCreatedDate));
            if (recentAssignment.isPresent())  {
                User alignedUser = recentAssignment.get().getAssignedUser();
                Optional<UserProductMap> alignedMapping = eligibleMappings.stream()
                        .filter(m -> m.getUser().getId().equals(alignedUser.getId()))
                        .findFirst();
                if (alignedMapping.isPresent()) {
                    logger.info("Aligned user {} (ID: {}) selected via contact details for company ID {}",
                            alignedUser.getFullName(), alignedUser.getId(), project.getCompany().getId());
                    return alignedMapping;
                }
            }
        }

        logger.debug("No aligned user found for milestone {}", milestone.getMilestone().getName());
        return Optional.empty();
    }

    private boolean isUserAvailable(User user, Long productId) {
        if (user == null || user.isDeleted() || !user.isActive()) return false;

        UserLoginStatus loginStatus = userLoginStatusRepository.findByUserIdAndIsDeletedFalse(user.getId()).orElse(null);
        if (loginStatus == null) return false;

        LocalDate today = LocalDate.now();
        boolean isOnline = loginStatus.isOnline() ||
                (loginStatus.getLastOnline() != null &&
                        loginStatus.getLastOnline().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().equals(today));

        UserPerformanceCount count = userPerformanceCountRepository.findByUserIdAndProductId(user.getId(), productId);
        int maxProjects = user.getBucketSize();
        boolean bucketOk = count == null || count.getAssignmentCount() < maxProjects;

        return isOnline && bucketOk;
    }

    /**
     * Fixed round-robin: product-wide, resets cycle, respects bucket.
     */
    private Optional<UserProductMap> selectRoundRobin(List<UserProductMap> eligibleMappings, Long productId) {
        logger.debug("Round-robin selection for {} eligible mappings, product ID: {}", eligibleMappings.size(), productId);

        if (eligibleMappings.isEmpty()) return Optional.empty();

        List<UserProductMap> allProductMappings = userProductMapRepository.findByProductIdAndIsDeletedFalse(productId);
        Set<Long> eligibleUserIds = eligibleMappings.stream().map(m -> m.getUser().getId()).collect(Collectors.toSet());

        List<UserProductMap> rrCandidates = allProductMappings.stream()
                .filter(m -> eligibleUserIds.contains(m.getUser().getId()))
                .collect(Collectors.toList());

        if (rrCandidates.isEmpty()) return Optional.empty();

        boolean allAssigned = rrCandidates.stream().allMatch(UserProductMap::isAssigned);
        if (allAssigned) {
            logger.info("Round-robin cycle complete for product ID {}, resetting flags", productId);
            rrCandidates.forEach(m -> m.setAssigned(false));
            userProductMapRepository.saveAll(rrCandidates);
        }



        Optional<UserProductMap> selected = rrCandidates.stream()
                .filter(m -> !m.isAssigned())
                .filter(m -> {
                    UserPerformanceCount cnt = userPerformanceCountRepository
                            .findByUserIdAndProductId(m.getUser().getId(), productId);
                    int max = m.getUser().getBucketSize();
                    return cnt == null || cnt.getAssignmentCount() < max;
                })
                .findFirst();

        selected.ifPresent(m -> {
            m.setAssigned(true);
            userProductMapRepository.save(m);
            logger.info("Round-robin selected user {} for product {}", m.getUser().getId(), productId);
        });

        return selected;
    }

    /**
     * Load-balanced selection when round-robin is OFF.
     */
    private Optional<UserProductMap> selectBestAvailable(List<UserProductMap> candidates, Long productId) {
        logger.debug("Best-available selection for {} candidates", candidates.size());

        return candidates.stream()
                .filter(m -> {
                    UserPerformanceCount cnt = userPerformanceCountRepository
                            .findByUserIdAndProductId(m.getUser().getId(), productId);
                    int max = m.getUser().getBucketSize();
                    return cnt == null || cnt.getAssignmentCount() < max;
                })
                .min(Comparator
                        .comparing((UserProductMap m) -> {
                            UserPerformanceCount cnt = userPerformanceCountRepository
                                    .findByUserIdAndProductId(m.getUser().getId(), productId);
                            return cnt != null ? cnt.getAssignmentCount() : 0;
                        })
                        .thenComparing(UserProductMap::getRating, Comparator.reverseOrder())
                        .thenComparing(m -> m.getUpdatedDate() != null ? m.getUpdatedDate() : new Date(0))
                );
    }



    private AssignmentResult assignUser(UserProductMap mapping, String reason, Long updatedById) {
        logger.info("Assigning user ID {} to milestone with reason: {}", mapping.getUser().getId(), reason);
        User user = mapping.getUser();

        mapping.setAssigned(true);
        userProductMapRepository.save(mapping);

        UserPerformanceCount count = userPerformanceCountRepository.findByUserIdAndProductId(user.getId(), mapping.getProduct().getId());
        if (count == null) {
            count = new UserPerformanceCount();
            count.setUser(user);
            count.setProduct(mapping.getProduct());
            count.setAssignmentCount(1);
            count.setTimeSpent(0.0);
            count.setLastUpdatedDate(new Date());
            count.setCreatedDate(new Date());
            count.setUpdatedDate(new Date());
            count.setCreatedBy(updatedById);
            count.setUpdatedBy(updatedById);
            count.setDeleted(false);
        } else {
            count.setAssignmentCount(count.getAssignmentCount() + 1);
            count.setLastUpdatedDate(new Date());
            count.setUpdatedDate(new Date());
            count.setUpdatedBy(updatedById);
        }
        userPerformanceCountRepository.save(count);

        return new AssignmentResult(user, reason);
    }

    private AssignmentResult assignFallbackManager(ProductMilestoneMap milestone, Department department, Long updatedById) {
        logger.info("Falling back to manager for milestone {}, department {}", milestone.getMilestone().getName(), department.getName());

        Optional<User> manager = userRepository.findManagerByDepartmentId(department.getId())
                .stream()
                .filter(u -> isUserAvailable(u, milestone.getProduct().getId()))
                .findFirst();

        if (manager.isPresent()) {
            UserProductMap managerMap = userProductMapRepository.findByUserIdAndProductIdAndIsDeletedFalse(manager.get().getId(), milestone.getProduct().getId())
                    .orElseGet(() -> {
                        UserProductMap newMap = new UserProductMap();
                        newMap.setUser(manager.get());
                        newMap.setProduct(milestone.getProduct());
                        newMap.setRating(0.0);
                        newMap.setAssigned(false);
                        newMap.setDeleted(false);
                        newMap.setCreatedDate(new Date());
                        newMap.setUpdatedDate(new Date());
                        newMap.setCreatedBy(updatedById);
                        newMap.setUpdatedBy(updatedById);
                        return newMap;
                    });
            return assignUser(managerMap, "Assigned to manager due to no available users", updatedById);
        }

        Optional<User> operationHead = userRepository.findAdmins()
                .stream()
                .filter(u -> isUserAvailable(u, milestone.getProduct().getId()))
                .findFirst();

        if (operationHead.isPresent()) {
            UserProductMap operationHeadMap = userProductMapRepository
                    .findByUserIdAndProductIdAndIsDeletedFalse(operationHead.get().getId(), milestone.getProduct().getId())
                    .orElseGet(() -> {
                        UserProductMap newMap = new UserProductMap();
                        newMap.setUser(operationHead.get());
                        newMap.setProduct(milestone.getProduct());
                        newMap.setRating(0.0);
                        newMap.setAssigned(false);
                        newMap.setDeleted(false);
                        newMap.setCreatedDate(new Date());
                        newMap.setUpdatedDate(new Date());
                        newMap.setCreatedBy(updatedById);
                        newMap.setUpdatedBy(updatedById);
                        return newMap;
                    });
            return assignUser(operationHeadMap, "Assigned to Operation Head due to no available manager or users", updatedById);
        }

        logger.warn("No available Operation Head for department {}, pending manual assignment", department.getName());
        return new AssignmentResult(null, "Pending manual assignment due to no available Operation Head or manager");
    }

    @Override
    public void updateDepartmentAutoConfig(DepartmentAutoConfigDto dto) {
        logger.info("Updating auto-config for department ID: {}, name: {}", dto.getDepartmentId(), dto.getDepartmentName());

        if (dto.isRatingPrioritizationEnabled() && !dto.isAvailabilityRequired() && !dto.getDepartmentName().equalsIgnoreCase("LEGAL")) {
            throw new ValidationException("Rating prioritization requires availability check unless department is LEGAL",
                    "INVALID_CONFIG_COMBINATION");
        }
        if (dto.isManualOnly() && (dto.isCompanyAlignmentEnabled() || dto.isAvailabilityRequired() ||
                dto.isRatingPrioritizationEnabled() || dto.isRoundRobinEnabled())) {
            throw new ValidationException("Manual-only mode cannot be combined with other auto-assignment features",
                    "INVALID_MANUAL_ONLY_COMBINATION");
        }

        Department department = departmentRepository.findByIdAndIsDeletedFalse(dto.getDepartmentId())
                .orElseThrow(() -> new ResourceNotFoundException("Department not found", "ERR_DEPARTMENT_NOT_FOUND"));

        DepartmentAutoConfig config = departmentAutoConfigRepository.findByDepartmentIdAndIsDeletedFalse(department.getId())
                .orElseGet(() -> {
                    DepartmentAutoConfig newConfig = new DepartmentAutoConfig();
                    newConfig.setDepartment(department);
                    newConfig.setCreatedDate(new Date());
                    return newConfig;
                });

        config.setAutoAssignmentEnabled(dto.isAutoAssignmentEnabled());
        config.setAvailabilityRequired(dto.isAvailabilityRequired());
        config.setRatingPrioritizationEnabled(dto.isRatingPrioritizationEnabled());
        config.setCompanyAlignmentEnabled(dto.isCompanyAlignmentEnabled());
        config.setManualOnly(dto.isManualOnly());
        config.setRoundRobinEnabled(dto.isRoundRobinEnabled());
        config.setUpdatedDate(new Date());

        departmentAutoConfigRepository.save(config);
        logger.info("Auto-config updated successfully for department: {}", department.getName());
    }

    @Override
    public DepartmentAutoConfigDto getDepartmentAutoConfig(Long departmentId) {
        logger.info("Fetching auto-config for department ID: {}", departmentId);

        Department department = departmentRepository.findByIdAndIsDeletedFalse(departmentId)
                .orElseThrow(() -> new ResourceNotFoundException("Department not found", "ERR_DEPARTMENT_NOT_FOUND"));

        DepartmentAutoConfig config = departmentAutoConfigRepository.findByDepartmentIdAndIsDeletedFalse(departmentId)
                .orElseGet(() -> {
                    DepartmentAutoConfig newConfig = new DepartmentAutoConfig();
                    newConfig.setDepartment(department);
                    newConfig.setAutoAssignmentEnabled(false);
                    newConfig.setAvailabilityRequired(true);
                    newConfig.setRatingPrioritizationEnabled(false);
                    newConfig.setCompanyAlignmentEnabled(false);
                    newConfig.setManualOnly(false);
                    newConfig.setRoundRobinEnabled(true);
                    return newConfig;
                });

        DepartmentAutoConfigDto dto = new DepartmentAutoConfigDto();
        dto.setDepartmentId(departmentId);
        dto.setDepartmentName(department.getName());
        dto.setAutoAssignmentEnabled(config.isAutoAssignmentEnabled());
        dto.setAvailabilityRequired(config.isAvailabilityRequired());
        dto.setRatingPrioritizationEnabled(config.isRatingPrioritizationEnabled());
        dto.setCompanyAlignmentEnabled(config.isCompanyAlignmentEnabled());
        dto.setManualOnly(config.isManualOnly());
        dto.setRoundRobinEnabled(config.isRoundRobinEnabled());

        logger.info("Auto-config fetched successfully for department: {}", department.getName());
        return dto;
    }
}