package com.doc.impl;

import com.doc.dto.DepartmentAutoConfigDto;
import com.doc.entity.department.Department;
import com.doc.entity.department.DepartmentAutoConfig;
import com.doc.entity.product.Product;
import com.doc.entity.product.ProductMilestoneMap;
import com.doc.entity.project.*;
import com.doc.entity.user.User;
import com.doc.entity.user.UserLoginStatus;
import com.doc.entity.user.UserProductMap;
import com.doc.exception.ResourceNotFoundException;
import com.doc.exception.ValidationException;
import com.doc.repository.*;
import com.doc.repository.department.DepartmentAutoConfigRepository;
import com.doc.service.AutoAssignmentService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.*;
import java.util.stream.Collectors;

@Service
@Transactional
public class AutoAssignmentServiceImpl implements AutoAssignmentService {

    private static final Logger logger = LoggerFactory.getLogger(AutoAssignmentServiceImpl.class);

    @Autowired private DepartmentAutoConfigRepository departmentAutoConfigRepository;
    @Autowired private UserRepository userRepository;
    @Autowired private UserProductMapRepository userProductMapRepository;
    @Autowired private UserPerformanceCountRepository userPerformanceCountRepository;
    @Autowired private UserLoginStatusRepository userLoginStatusRepository;
    @Autowired private DepartmentRepository departmentRepository;
    @Autowired private ProjectAssignmentHistoryRepository projectAssignmentHistoryRepository;
    @Autowired private ProjectMilestoneAssignmentRepository projectMilestoneAssignmentRepository;
    @Autowired private MilestoneStatusRepository milestoneStatusRepository;

    @Override
    public AssignmentResult assignMilestoneUser(ProductMilestoneMap milestone, Project project, Long updatedById) {
        logger.info("=== AUTO-ASSIGNMENT START ===");
        logger.info("Milestone: {} | Product: {} | Project: {}",
                milestone.getMilestone().getName(), milestone.getProduct().getId(), project.getProjectNo());

        if (!milestone.isMandatory()) {
            logger.info("Non-mandatory milestone → skipped");
            return new AssignmentResult(null, "Skipped non-mandatory");
        }
        if (milestone.isAutoGenerated()) {
            logger.info("Auto-generated milestone → skipped");
            return null;
        }

        List<Department> depts = milestone.getMilestone().getDepartments();
        if (depts.isEmpty()) {
            logger.warn("No department linked → queuing");
            queueMilestone(milestone, project, updatedById);
            return new AssignmentResult(null, "Queued: no department");
        }

        Department dept = depts.get(0);
        DepartmentAutoConfig config = getOrCreateConfig(dept);

        logger.info("CONFIG → Dept: {} | Enabled: {} | RR: {} | Rating: {} | Align: {} | ManualOnly: {}",
                dept.getName(), config.isAutoAssignmentEnabled(), config.isRoundRobinEnabled(),
                config.isRatingPrioritizationEnabled(), config.isCompanyAlignmentEnabled(), config.isManualOnly());

        if (!config.isAutoAssignmentEnabled() || config.isManualOnly()) {
            logger.info("Auto-assignment OFF → manual");
            return new AssignmentResult(null, "Pending manual assignment");
        }

        // 1. Get ACTIVE users in department
        List<User> deptUsers = userRepository.findByDepartmentsIdAndIsActiveTrueAndIsDeletedFalse(dept.getId());
        logger.info("Found {} ACTIVE users in dept '{}'", deptUsers.size(), dept.getName());

        if (deptUsers.isEmpty()) {
            logger.warn("No active users in dept → fallback");
            return assignFallbackManager(milestone, dept, project, updatedById);
        }

        // 2. Get product mappings
        List<UserProductMap> mappings = userProductMapRepository.findByProductIdAndIsDeletedFalse(milestone.getProduct().getId());
        logger.info("Found {} product mappings for Product {}", mappings.size(), milestone.getProduct().getId());

        // 3. Build eligible list
        List<UserProductMap> eligible = mappings.stream()
                .filter(m -> deptUsers.stream().anyMatch(u -> u.getId().equals(m.getUser().getId())))
                .filter(m -> !config.isRatingPrioritizationEnabled() || (m.getRating() != null && m.getRating() > 0))
                .filter(m -> !config.isAvailabilityRequired() || isUserAvailable(m.getUser(), milestone.getProduct().getId(), project, dept, config))
                .sorted(Comparator.comparing(m -> m.getUser().getFullName()))
                .collect(Collectors.toList());

        logger.info("ELIGIBLE USERS ({}): {}", eligible.size(),
                eligible.stream()
                        .map(m -> m.getUser().getFullName() +
                                " (active=" + m.getUser().isActive() +
                                ", online=" + isUserOnline(m.getUser()) +
                                ", bucket=" + isBucketAvailable(m.getUser(), milestone.getProduct().getId()) +
                                ", rating=" + m.getRating() + ")")
                        .collect(Collectors.joining(", ")));


        if (eligible.isEmpty()) {
            logger.warn("No eligible users → fallback");
            return assignFallbackManager(milestone, dept, project, updatedById);
        }

        // 4. COMPANY ALIGNMENT (ONLY when enabled)
        if (config.isCompanyAlignmentEnabled()) {
            logger.info("COMPANY ALIGNMENT ENABLED → checking history with Company ID: {}", project.getCompany().getId());

            List<ProjectAssignmentHistory> history = projectAssignmentHistoryRepository
                    .findByProjectCompanyIdAndMilestoneIdAndDepartmentId(
                            project.getCompany().getId(),
                            milestone.getMilestone().getId(),
                            dept.getId());

            if (history.isEmpty()) {
                logger.info("No prior history with this company");
            } else {
                Set<Long> pastUserIds = history.stream()
                        .filter(h -> h.getAssignedUser() != null)
                        .map(h -> h.getAssignedUser().getId())
                        .collect(Collectors.toSet());

                List<UserProductMap> aligned = eligible.stream()
                        .filter(m -> pastUserIds.contains(m.getUser().getId()))
                        .collect(Collectors.toList());

                logger.info("COMPANY HISTORY MATCH → {} users: {}", aligned.size(),
                        aligned.stream().map(m -> m.getUser().getFullName()).collect(Collectors.joining(", ")));

                if (!aligned.isEmpty()) {
                    UserProductMap chosen = aligned.get(0); // stable order
                    logger.info("COMPANY-ALIGNED USER SELECTED: {}", chosen.getUser().getFullName());
                    return assignUser(chosen, "Assigned: company alignment", updatedById);
                }
            }
        }

        // 5. RATING + RR
        if (config.isRatingPrioritizationEnabled()) {
            logger.info("RATING PRIORITIZATION ENABLED");
            Map<Double, List<UserProductMap>> groups = eligible.stream()
                    .collect(Collectors.groupingBy(UserProductMap::getRating));
            List<Double> tiers = new ArrayList<>(groups.keySet());
            tiers.sort(Comparator.reverseOrder());

            for (Double tier : tiers) {
                List<UserProductMap> tierUsers = groups.get(tier);
                Optional<UserProductMap> selected = config.isRoundRobinEnabled()
                        ? selectRoundRobin(tierUsers, milestone.getProduct().getId(), false)
                        : selectBestAvailable(tierUsers, milestone.getProduct().getId());
                if (selected.isPresent()) {
                    String reason = "Assigned: " + tier + "-star" + (config.isRoundRobinEnabled() ? " + RR" : " + load");
                    logger.info("RATING SELECTED: {} → {}", selected.get().getUser().getFullName(), reason);
                    return assignUser(selected.get(), reason, updatedById);
                }

            }
        }

        // 6. PURE RR or LOAD BALANCE
        Optional<UserProductMap> selected = config.isRoundRobinEnabled()
                ? selectRoundRobin(eligible, milestone.getProduct().getId(), false)
                : selectBestAvailable(eligible, milestone.getProduct().getId());

        if (selected.isPresent()) {
            String reason = config.isRoundRobinEnabled() ? "Assigned: round-robin" : "Assigned: load balance";
            logger.info("FINAL SELECTED: {} → {}", selected.get().getUser().getFullName(), reason);
            return assignUser(selected.get(), reason, updatedById);
        }

        // 7. FORCE ASSIGN
        selected = selectRoundRobin(eligible, milestone.getProduct().getId(), true);
        if (selected.isPresent()) {
            logger.info("FORCE-ASSIGNED: {} (buckets full)", selected.get().getUser().getFullName());
            return assignUser(selected.get(), "FORCE-Assigned: all buckets full", updatedById);
        }

        logger.warn("No assignment possible → fallback");
        return assignFallbackManager(milestone, dept, project, updatedById);
    }

    private boolean isUserOnline(User user) {
        UserLoginStatus status = userLoginStatusRepository.findByUserIdAndIsDeletedFalse(user.getId()).orElse(null);
        if (status == null) return false;
        LocalDate today = LocalDate.now();
        return status.isOnline() ||
                (status.getLastOnline() != null &&
                        status.getLastOnline().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().equals(today));
    }

    private boolean isBucketAvailable(User user, Long productId) {
        UserPerformanceCount cnt = userPerformanceCountRepository.findByUserIdAndProductId(user.getId(), productId);
        return cnt == null || cnt.getAssignmentCount() < user.getBucketSize();
    }

    private DepartmentAutoConfig getOrCreateConfig(Department dept) {
        return departmentAutoConfigRepository.findByDepartmentIdAndIsDeletedFalse(dept.getId())
                .orElseGet(() -> {
                    DepartmentAutoConfig cfg = new DepartmentAutoConfig();
                    cfg.setDepartment(dept);
                    cfg.setAutoAssignmentEnabled(false);
                    cfg.setRoundRobinEnabled(true);
                    cfg.setCreatedDate(new Date());
                    return departmentAutoConfigRepository.save(cfg);
                });
    }


    private Optional<UserProductMap> selectRoundRobin(List<UserProductMap> candidates, Long productId, boolean ignoreBucket) {
        if (candidates.isEmpty()) return Optional.empty();

        List<UserProductMap> sorted = candidates.stream()
                .sorted(Comparator.comparing(m -> m.getUser().getFullName()))
                .collect(Collectors.toList());

        Set<Long> ids = sorted.stream().map(m -> m.getUser().getId()).collect(Collectors.toSet());
        List<UserProductMap> pool = userProductMapRepository.findByProductIdAndIsDeletedFalse(productId).stream()
                .filter(m -> ids.contains(m.getUser().getId()))
                .sorted(Comparator.comparing(m -> m.getUser().getFullName()))
                .collect(Collectors.toList());

        if (pool.stream().allMatch(UserProductMap::isAssigned)) {
            pool.forEach(m -> m.setAssigned(false));
            userProductMapRepository.saveAll(pool);
        }

        return pool.stream()
                .filter(m -> !m.isAssigned())
                .filter(m -> ignoreBucket || isBucketAvailable(m.getUser(), productId))
                .findFirst()
                .or(() -> {
                    pool.forEach(m -> m.setAssigned(false));
                    userProductMapRepository.saveAll(pool);
                    return pool.stream()
                            .filter(m -> ignoreBucket || isBucketAvailable(m.getUser(), productId))
                            .findFirst();
                });
    }

    private Optional<UserProductMap> selectBestAvailable(List<UserProductMap> candidates, Long productId) {
        return candidates.stream()
                .filter(m -> isBucketAvailable(m.getUser(), productId))
                .min(Comparator.comparing((UserProductMap m) -> {
                    UserPerformanceCount c = userPerformanceCountRepository.findByUserIdAndProductId(m.getUser().getId(), productId);
                    return c != null ? c.getAssignmentCount() : 0;
                }).thenComparing(UserProductMap::getRating, Comparator.reverseOrder()));
    }

    private boolean isUserAvailable(User user, Long productId, Project project, Department dept, DepartmentAutoConfig config) {
        if (!user.isActive()) {
            logger.debug("User {} is INACTIVE → excluded", user.getFullName());
            return false;
        }

        UserLoginStatus status = userLoginStatusRepository.findByUserIdAndIsDeletedFalse(user.getId()).orElse(null);
        if (status == null) return false;

        boolean online = status.isOnline() ||
                (status.getLastOnline() != null &&
                        status.getLastOnline().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().equals(LocalDate.now()));

        if (!online && config.isCompanyAlignmentEnabled()) {
            boolean hasHistory = projectAssignmentHistoryRepository
                    .existsByProjectCompanyIdAndAssignedUserIdAndDepartmentId(project.getCompany().getId(), user.getId(), dept.getId());
            if (hasHistory) {
                logger.info("OFFLINE user {} ALLOWED due to company history", user.getFullName());
                return true;
            }
        }

        return online && isBucketAvailable(user, productId);
    }

    private AssignmentResult assignUser(UserProductMap mapping, String reason, Long updatedById) {
        mapping.setAssigned(true);
        userProductMapRepository.save(mapping);

        User user = mapping.getUser();
        UserPerformanceCount count = userPerformanceCountRepository.findByUserIdAndProductId(user.getId(), mapping.getProduct().getId());
        if (count == null) {
            count = new UserPerformanceCount();
            count.setUser(user);
            count.setProduct(mapping.getProduct());
            count.setAssignmentCount(1);
            count.setTimeSpent(0.0);
            count.setCreatedDate(new Date());
            count.setCreatedBy(updatedById);
            count.setDeleted(false);
        } else {
            count.setAssignmentCount(count.getAssignmentCount() + 1);
        }
        count.setLastUpdatedDate(new Date());
        count.setUpdatedDate(new Date());
        count.setUpdatedBy(updatedById);
        userPerformanceCountRepository.save(count);

        logger.info("FINAL ASSIGNMENT → {} | Reason: {}", user.getFullName(), reason);
        return new AssignmentResult(user, reason);
    }

    private AssignmentResult assignFallbackManager(ProductMilestoneMap milestone, Department department, Project project, Long updatedById) {
        logger.info("FALLBACK: Trying manager → dept {}", department.getName());

        Optional<User> manager = userRepository.findManagerByDepartmentId(department.getId()).stream()
                .filter(u -> isUserAvailable(u, milestone.getProduct().getId(), project, department, getOrCreateConfig(department)))
                .findFirst();

        if (manager.isPresent()) {
            UserProductMap map = userProductMapRepository.findByUserIdAndProductIdAndIsDeletedFalse(manager.get().getId(), milestone.getProduct().getId())
                    .orElseGet(() -> createMap(manager.get(), milestone.getProduct(), updatedById));
            return assignUser(map, "Assigned to manager", updatedById);
        }

        Optional<User> opHead = userRepository.findAdmins().stream()
                .filter(u -> isUserAvailable(u, milestone.getProduct().getId(), project, department, getOrCreateConfig(department)))
                .findFirst();

        if (opHead.isPresent()) {
            UserProductMap map = userProductMapRepository.findByUserIdAndProductIdAndIsDeletedFalse(opHead.get().getId(), milestone.getProduct().getId())
                    .orElseGet(() -> createMap(opHead.get(), milestone.getProduct(), updatedById));
            return assignUser(map, "Assigned to Operation Head", updatedById);
        }

        logger.warn("NO ONE AVAILABLE → manual assignment");
        return new AssignmentResult(null, "Pending manual assignment");
    }

    private UserProductMap createMap(User user, Product product, Long updatedById) {
        UserProductMap map = new UserProductMap();
        map.setUser(user);
        map.setProduct(product);
        map.setRating(0.0);
        map.setAssigned(false);
        map.setDeleted(false);
        map.setCreatedDate(new Date());
        map.setUpdatedDate(new Date());
        map.setCreatedBy(updatedById);
        map.setUpdatedBy(updatedById);
        return userProductMapRepository.save(map);
    }

    private void queueMilestone(ProductMilestoneMap milestone, Project project, Long updatedById) {
        ProjectMilestoneAssignment assignment = projectMilestoneAssignmentRepository
                .findByProjectIdAndMilestoneIdAndIsDeletedFalse(project.getId(), milestone.getMilestone().getId())
                .orElseThrow(() -> new ResourceNotFoundException("Assignment not found", "ERR_ASSIGNMENT_NOT_FOUND"));

        MilestoneStatus queued = milestoneStatusRepository.findByName("QUEUED")
                .orElseThrow(() -> new ResourceNotFoundException("QUEUED status not found", "ERR_STATUS_NOT_FOUND"));

        assignment.setStatus(queued);
        assignment.setStatusReason("Queued due to no department mapping");
        assignment.setUpdatedBy(updatedById);
        assignment.setUpdatedDate(new Date());
        projectMilestoneAssignmentRepository.save(assignment);

        ProjectAssignmentHistory history = new ProjectAssignmentHistory();
        history.setProject(project);
        history.setMilestoneAssignment(assignment);
        history.setAssignmentReason("Queued due to no department mapping");
        history.setCreatedDate(new Date());
        history.setUpdatedDate(new Date());
        history.setCreatedBy(updatedById);
        history.setUpdatedBy(updatedById);
        history.setDeleted(false);
        projectAssignmentHistoryRepository.save(history);
    }

    @Override
    public void updateDepartmentAutoConfig(DepartmentAutoConfigDto dto) {
        logger.info("Updating auto-config for department ID: {}, name: {}", dto.getDepartmentId(), dto.getDepartmentName());

        if (dto.isRatingPrioritizationEnabled() && !dto.isAvailabilityRequired() && !dto.getDepartmentName().equalsIgnoreCase("LEGAL")) {
            throw new ValidationException("Rating prioritization requires availability check unless department is LEGAL", "INVALID_CONFIG_COMBINATION");
        }
        if (dto.isManualOnly() && (dto.isCompanyAlignmentEnabled() || dto.isAvailabilityRequired() ||
                dto.isRatingPrioritizationEnabled() || dto.isRoundRobinEnabled())) {
            throw new ValidationException("Manual-only mode cannot be combined with other auto-assignment features", "INVALID_MANUAL_ONLY_COMBINATION");
        }

        Department department = departmentRepository.findByIdAndIsDeletedFalse(dto.getDepartmentId())
                .orElseThrow(() -> new ResourceNotFoundException("Department not found", "ERR_DEPARTMENT_NOT_FOUND"));

        DepartmentAutoConfig config = departmentAutoConfigRepository.findByDepartmentIdAndIsDeletedFalse(department.getId())
                .orElseGet(() -> {
                    DepartmentAutoConfig newConfig = new DepartmentAutoConfig();
                    newConfig.setDepartment(department);
                    newConfig.setCreatedDate(new Date());
                    return newConfig;
                });

        config.setAutoAssignmentEnabled(dto.isAutoAssignmentEnabled());
        config.setAvailabilityRequired(dto.isAvailabilityRequired());
        config.setRatingPrioritizationEnabled(dto.isRatingPrioritizationEnabled());
        config.setCompanyAlignmentEnabled(dto.isCompanyAlignmentEnabled());
        config.setManualOnly(dto.isManualOnly());
        config.setRoundRobinEnabled(dto.isRoundRobinEnabled());
        config.setUpdatedDate(new Date());

        departmentAutoConfigRepository.save(config);
        logger.info("Auto-config updated successfully for department: {}", department.getName());
    }

    @Override
    public DepartmentAutoConfigDto getDepartmentAutoConfig(Long departmentId) {
        logger.info("Fetching auto-config for department ID: {}", departmentId);

        Department department = departmentRepository.findByIdAndIsDeletedFalse(departmentId)
                .orElseThrow(() -> new ResourceNotFoundException("Department not found", "ERR_DEPARTMENT_NOT_FOUND"));

        DepartmentAutoConfig config = departmentAutoConfigRepository.findByDepartmentIdAndIsDeletedFalse(departmentId)
                .orElseGet(() -> {
                    DepartmentAutoConfig newConfig = new DepartmentAutoConfig();
                    newConfig.setDepartment(department);
                    newConfig.setAutoAssignmentEnabled(false);
                    newConfig.setAvailabilityRequired(true);
                    newConfig.setRatingPrioritizationEnabled(false);
                    newConfig.setCompanyAlignmentEnabled(false);
                    newConfig.setManualOnly(false);
                    newConfig.setRoundRobinEnabled(true);
                    return newConfig;
                });

        DepartmentAutoConfigDto dto = new DepartmentAutoConfigDto();
        dto.setDepartmentId(departmentId);
        dto.setDepartmentName(department.getName());
        dto.setAutoAssignmentEnabled(config.isAutoAssignmentEnabled());
        dto.setAvailabilityRequired(config.isAvailabilityRequired());
        dto.setRatingPrioritizationEnabled(config.isRatingPrioritizationEnabled());
        dto.setCompanyAlignmentEnabled(config.isCompanyAlignmentEnabled());
        dto.setManualOnly(config.isManualOnly());
        dto.setRoundRobinEnabled(config.isRoundRobinEnabled());

        logger.info("Auto-config fetched successfully for department: {}", department.getName());
        return dto;
    }
}