package com.doc.impl;


import com.doc.dto.ProjectMilestoneassignment.ReassignMilestoneDto;
import com.doc.dto.ProjectMilestoneassignment.UpdateMilestoneStatusDto;
import com.doc.entity.product.ProductMilestoneMap;
import com.doc.entity.project.*;
import com.doc.entity.user.Department;
import com.doc.entity.user.User;
import com.doc.entity.user.UserProductMap;
import com.doc.exception.ResourceNotFoundException;
import com.doc.exception.ValidationException;
import com.doc.repository.*;
import com.doc.service.ProjectMilestoneAssignmentService;
import com.doc.service.ProjectService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

@Service
@Transactional
public class ProjectMilestoneAssignmentServiceImpl implements ProjectMilestoneAssignmentService {

    private static final Logger logger = LoggerFactory.getLogger(ProjectMilestoneAssignmentServiceImpl.class);

    @Autowired
    private ProjectMilestoneAssignmentRepository projectMilestoneAssignmentRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private ProjectDocumentUploadRepository projectDocumentUploadRepository;

    @Autowired
    private MilestoneStatusHistoryRepository milestoneStatusHistoryRepository;

    @Autowired
    private ProjectService projectService;

    @Autowired
    private ProjectRepository projectRepository;

    @Autowired
    private ProjectAssignmentHistoryRepository projectAssignmentHistoryRepository;

    @Autowired
    private UserProductMapRepository userProductMapRepository;

    @Autowired
    private UserProjectCountRepository userProjectCountRepository;

    @Override
    public void updateMilestoneStatus(UpdateMilestoneStatusDto updateDto) {
        // Existing updateMilestoneStatus implementation (unchanged from your provided code)
        logger.info("Updating milestone assignment ID: {} to status: {}", updateDto.getAssignmentId(), updateDto.getNewStatus());
        ProjectMilestoneAssignment assignment = projectMilestoneAssignmentRepository.findByIdAndIsDeletedFalse(updateDto.getAssignmentId())
                .orElseThrow(() -> {
                    logger.error("Milestone assignment with ID {} not found or is deleted", updateDto.getAssignmentId());
                    return new ResourceNotFoundException("Milestone assignment with ID " + updateDto.getAssignmentId() + " not found or is deleted");
                });

        User changedBy = userRepository.findByIdAndIsDeletedFalse(updateDto.getChangedById())
                .orElseThrow(() -> {
                    logger.error("User with ID {} not found or is deleted", updateDto.getChangedById());
                    return new ResourceNotFoundException("User with ID " + updateDto.getChangedById() + " not found or is deleted");
                });

        validateMilestoneStatusTransition(assignment, updateDto.getNewStatus(), updateDto.getStatusReason());

        if (updateDto.getNewStatus() == MilestoneStatus.COMPLETED) {
            List<ProjectDocumentUpload> documents = projectDocumentUploadRepository.findByMilestoneAssignmentIdAndIsDeletedFalse(updateDto.getAssignmentId());
            if (!assignment.getProductMilestoneMap().isAutoGenerated() && !documents.isEmpty()) {
                boolean allVerified = documents.stream().allMatch(doc -> doc.getStatus() == DocumentStatus.VERIFIED);
                if (!allVerified) {
                    logger.warn("Cannot complete milestone ID: {} due to unverified documents", updateDto.getAssignmentId());
                    throw new ValidationException("All documents must be verified to complete milestone");
                }
            }
        }

        if (updateDto.getNewStatus() == MilestoneStatus.NEW && assignment.getStatus() == MilestoneStatus.REJECTED) {
            if (!assignment.getProductMilestoneMap().isAllowRollback()) {
                logger.warn("Rollback not allowed for milestone: {}", assignment.getProductMilestoneMap().getMilestone().getName());
                throw new ValidationException("Rollback not allowed for milestone " + assignment.getProductMilestoneMap().getMilestone().getName());
            }
            if (assignment.getReworkAttempts() >= assignment.getProductMilestoneMap().getMaxAttempts()) {
                logger.warn("Maximum rework attempts ({}) reached for milestone ID: {}",
                        assignment.getProductMilestoneMap().getMaxAttempts(), updateDto.getAssignmentId());
                throw new ValidationException("Maximum rework attempts reached for milestone");
            }
            assignment.setReworkAttempts(assignment.getReworkAttempts() + 1);
        }

        MilestoneStatusHistory history = new MilestoneStatusHistory();
        history.setMilestoneAssignment(assignment);
        history.setPreviousStatus(assignment.getStatus());
        history.setNewStatus(updateDto.getNewStatus());
        history.setChangeReason(updateDto.getStatusReason());
        history.setChangedBy(changedBy);
        history.setChangeDate(new Date());
        history.setDeleted(false);

        assignment.setStatus(updateDto.getNewStatus());
        assignment.setStatusReason(updateDto.getStatusReason());
        if (updateDto.getNewStatus() == MilestoneStatus.IN_PROGRESS) {
            assignment.setStartedDate(new Date());
        } else if (updateDto.getNewStatus() == MilestoneStatus.COMPLETED) {
            assignment.setCompletedDate(new Date());
        } else if (updateDto.getNewStatus() == MilestoneStatus.REJECTED || updateDto.getNewStatus() == MilestoneStatus.ON_HOLD) {
            assignment.setStatusReason(updateDto.getStatusReason());
        }
        assignment.setUpdatedBy(updateDto.getChangedById());
        assignment.setUpdatedDate(new Date());

        projectMilestoneAssignmentRepository.save(assignment);
        milestoneStatusHistoryRepository.save(history);
        logger.info("Milestone assignment ID: {} updated to status: {}", updateDto.getAssignmentId(), updateDto.getNewStatus());

        Project project = assignment.getProject();
        updateProjectStatus(project, updateDto.getChangedById());

        if (updateDto.getNewStatus() == MilestoneStatus.COMPLETED) {
            projectService.updateMilestoneVisibilities(project, updateDto.getChangedById());
        }
    }

    @Override
    public void reassignMilestone(ReassignMilestoneDto reassignDto) {

        logger.info("Reassigning milestone assignment ID: {} to user ID: {}", reassignDto.getAssignmentId(), reassignDto.getNewUserId());

        // Validate milestone assignment
        ProjectMilestoneAssignment assignment = projectMilestoneAssignmentRepository.findByIdAndIsDeletedFalse(reassignDto.getAssignmentId())
                .orElseThrow(() -> {
                    logger.error("Milestone assignment with ID {} not found or is deleted", reassignDto.getAssignmentId());
                    return new ResourceNotFoundException("Milestone assignment with ID " + reassignDto.getAssignmentId() + " not found or is deleted");
                });

        // Validate new user
        User newUser = userRepository.findByIdAndIsDeletedFalse(reassignDto.getNewUserId())
                .orElseThrow(() -> {
                    logger.error("User with ID {} not found or is deleted", reassignDto.getNewUserId());
                    return new ResourceNotFoundException("User with ID " + reassignDto.getNewUserId() + " not found or is deleted");
                });

        // Validate changedBy user
        User changedBy = userRepository.findByIdAndIsDeletedFalse(reassignDto.getChangedById())
                .orElseThrow(() -> {
                    logger.error("User with ID {} not found or is deleted", reassignDto.getChangedById());
                    return new ResourceNotFoundException("User with ID " + reassignDto.getChangedById() + " not found or is deleted");
                });

        // Validate reassignment reason
        if (reassignDto.getReassignmentReason() == null || reassignDto.getReassignmentReason().trim().isEmpty()) {
            logger.warn("Reassignment reason is required for milestone assignment ID: {}", reassignDto.getAssignmentId());
            throw new ValidationException("Reassignment reason is required");
        }

        // Validate that the milestone is not completed
        if (assignment.getStatus() == MilestoneStatus.COMPLETED) {
            logger.warn("Cannot reassign completed milestone assignment ID: {}", reassignDto.getAssignmentId());
            throw new ValidationException("Cannot reassign a completed milestone");
        }

        // Validate that the new user is different from the current user
        if (assignment.getAssignedUser() != null && assignment.getAssignedUser().getId().equals(reassignDto.getNewUserId())) {
            logger.warn("Milestone assignment ID: {} is already assigned to user ID: {}", reassignDto.getAssignmentId(), reassignDto.getNewUserId());
            throw new ValidationException("Milestone is already assigned to the specified user");
        }

        // Validate that the new user is eligible (belongs to the milestone's department)
        ProductMilestoneMap milestoneMap = assignment.getProductMilestoneMap();
        if (!milestoneMap.isAutoGenerated()) {
            List<Long> milestoneDepartmentIds = milestoneMap.getMilestone().getDepartments().stream()
                    .map(Department::getId)
                    .collect(Collectors.toList());
            List<Long> userDepartmentIds = newUser.getDepartments().stream()
                    .map(Department::getId)
                    .collect(Collectors.toList());
            boolean isEligible = userDepartmentIds.stream().anyMatch(milestoneDepartmentIds::contains);
            if (!isEligible) {
                logger.warn("User ID: {} is not eligible for milestone: {}", reassignDto.getNewUserId(), milestoneMap.getMilestone().getName());
                throw new ValidationException("User is not in a department associated with the milestone");
            }
        }

        // Update UserProductMap for the old user (if exists)
        if (assignment.getAssignedUser() != null) {
            UserProductMap oldUserMap = userProductMapRepository.findByUserIdAndProductIdAndIsDeletedFalse(
                            assignment.getAssignedUser().getId(), assignment.getProject().getProduct().getId())
                    .orElse(null);
            if (oldUserMap != null) {
                oldUserMap.setAssigned(false);
                userProductMapRepository.save(oldUserMap);
                logger.debug("Reset isAssigned for user ID: {} in UserProductMap", assignment.getAssignedUser().getId());
            }
        }

        // Update UserProductMap for the new user
        UserProductMap newUserMap = userProductMapRepository.findByUserIdAndProductIdAndIsDeletedFalse(
                        newUser.getId(), assignment.getProject().getProduct().getId())
                .orElseGet(() -> {
                    UserProductMap map = new UserProductMap();
                    map.setUser(newUser);
                    map.setProduct(assignment.getProject().getProduct());
                    map.setRating(0.0);
                    map.setAssigned(false);
                    map.setDeleted(false);
                    map.setCreatedDate(new Date());
                    map.setUpdatedDate(new Date());
                    map.setCreatedBy(reassignDto.getChangedById());
                    map.setUpdatedBy(reassignDto.getChangedById());
                    return map;
                });
        newUserMap.setAssigned(true);
        userProductMapRepository.save(newUserMap);
        logger.debug("Set isAssigned to true for user ID: {} in UserProductMap", newUser.getId());

        // Update UserProjectCount for the new user
        UserProjectCount count = userProjectCountRepository.findByUserIdAndProductId(newUser.getId(), assignment.getProject().getProduct().getId());
        if (count == null) {
            count = new UserProjectCount();
            count.setUser(newUser);
            count.setProduct(assignment.getProject().getProduct());
            count.setProjectCount(1);
            count.setLastUpdatedDate(new Date());
            count.setCreatedDate(new Date());
            count.setUpdatedDate(new Date());
            count.setCreatedBy(reassignDto.getChangedById());
            count.setUpdatedBy(reassignDto.getChangedById());
            count.setDeleted(false);
        } else {
            count.setProjectCount(count.getProjectCount() + 1);
            count.setLastUpdatedDate(new Date());
            count.setUpdatedDate(new Date());
            count.setUpdatedBy(reassignDto.getChangedById());
        }
        userProjectCountRepository.save(count);
        logger.debug("Updated UserProjectCount for user ID: {}", newUser.getId());

        // Log reassignment in ProjectAssignmentHistory
        ProjectAssignmentHistory history = new ProjectAssignmentHistory();
        history.setProject(assignment.getProject());
        history.setMilestoneAssignment(assignment);
        history.setAssignedUser(newUser);
        history.setAssignmentReason(reassignDto.getReassignmentReason());
        history.setCreatedDate(new Date());
        history.setUpdatedDate(new Date());
        history.setCreatedBy(reassignDto.getChangedById());
        history.setUpdatedBy(reassignDto.getChangedById());
        history.setDeleted(false);
        projectAssignmentHistoryRepository.save(history);
        logger.debug("Logged reassignment for milestone assignment ID: {} to user ID: {}", reassignDto.getAssignmentId(), newUser.getId());

        // Update the assignment
        assignment.setAssignedUser(newUser);
        assignment.setUpdatedBy(reassignDto.getChangedById());
        assignment.setUpdatedDate(new Date());
        projectMilestoneAssignmentRepository.save(assignment);
        logger.info("Milestone assignment ID: {} reassigned to user ID: {}", reassignDto.getAssignmentId(), reassignDto.getNewUserId());
    }

    private void validateMilestoneStatusTransition(ProjectMilestoneAssignment assignment, MilestoneStatus newStatus, String statusReason) {
        if (statusReason == null || statusReason.trim().isEmpty()) {
            if (newStatus == MilestoneStatus.COMPLETED || newStatus == MilestoneStatus.ON_HOLD || newStatus == MilestoneStatus.REJECTED) {
                logger.warn("Status reason is required for status: {}", newStatus);
                throw new ValidationException("Status reason is required for status: " + newStatus);
            }
        }

        MilestoneStatus currentStatus = assignment.getStatus();
        if (currentStatus == newStatus) {
            logger.warn("Milestone assignment ID: {} already in status: {}", assignment.getId(), newStatus);
            throw new ValidationException("Milestone is already in status: " + newStatus);
        }

        switch (currentStatus) {
            case NEW:
                if (newStatus != MilestoneStatus.IN_PROGRESS && newStatus != MilestoneStatus.ON_HOLD) {
                    throw new ValidationException("Invalid transition from NEW to " + newStatus);
                }
                break;
            case IN_PROGRESS:
                if (newStatus != MilestoneStatus.COMPLETED && newStatus != MilestoneStatus.ON_HOLD && newStatus != MilestoneStatus.REJECTED) {
                    throw new ValidationException("Invalid transition from IN_PROGRESS to " + newStatus);
                }
                break;
            case ON_HOLD:
                if (newStatus != MilestoneStatus.IN_PROGRESS) {
                    throw new ValidationException("Invalid transition from ON_HOLD to " + newStatus);
                }
                break;
            case REJECTED:
                if (newStatus != MilestoneStatus.NEW) {
                    throw new ValidationException("Invalid transition from REJECTED to " + newStatus);
                }
                break;
            case COMPLETED:
                throw new ValidationException("Cannot change status from COMPLETED");
            default:
                throw new ValidationException("Invalid current status: " + currentStatus);
        }

        if (!assignment.isVisible() && newStatus != MilestoneStatus.NEW) {
            logger.warn("Cannot update milestone ID: {} to {} when not visible", assignment.getId(), newStatus);
            throw new ValidationException("Milestone must be visible to change status to " + newStatus);
        }
    }

    private void updateProjectStatus(Project project, Long updatedById) {
        logger.debug("Updating project status for project ID: {}", project.getId());
        List<ProjectMilestoneAssignment> assignments = projectMilestoneAssignmentRepository.findByProjectIdAndIsDeletedFalse(project.getId());

        if (assignments.isEmpty()) {
            project.setStatus(ProjectStatus.OPEN);
        } else if (assignments.stream().allMatch(a -> a.getStatus() == MilestoneStatus.COMPLETED)) {
            project.setStatus(ProjectStatus.COMPLETED);
        } else if (assignments.stream().anyMatch(a -> a.getStatus() == MilestoneStatus.IN_PROGRESS || a.getStatus() == MilestoneStatus.ON_HOLD)) {
            project.setStatus(ProjectStatus.IN_PROGRESS);
        } else {
            project.setStatus(ProjectStatus.OPEN);
        }

        project.setUpdatedBy(updatedById);
        project.setUpdatedDate(new Date());
        projectRepository.save(project);
        logger.debug("Project ID: {} status updated to: {}", project.getId(), project.getStatus());
    }
}