package com.doc.em;

public enum ProjectHistoryEventType {
    PROJECT_CREATED,
    PROJECT_STATUS_CHANGED,
    PROJECT_PRIORITY_CHANGED,
    PROJECT_CANCELLED,
    PROJECT_FORCE_CLOSE_REQUESTED,
    PROJECT_FORCE_CLOSE_APPROVED,
    PROJECT_FORCE_CLOSE_REJECTED,
    PROJECT_REOPEN_REQUESTED,
    PROJECT_REOPEN_APPROVED,
    PROJECT_REOPEN_REJECTED,

    MILESTONE_CREATED,
    MILESTONE_VISIBILITY_CHANGED,
    MILESTONE_ASSIGNED,
    MILESTONE_REASSIGNED,
    MILESTONE_STATUS_CHANGED,
    MILESTONE_SENT_BACK,
    MILESTONE_ON_HOLD_REQUESTED,
    MILESTONE_ON_HOLD_APPROVED,
    MILESTONE_ON_HOLD_REJECTED,

    DOCUMENT_UPLOADED,
    DOCUMENT_REPLACED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,
    DOCUMENT_EXPIRED,

    LEGAL_REQUEST_RAISED,
    LEGAL_REQUEST_ASSIGNED,
    LEGAL_REQUEST_REASSIGNED,
    LEGAL_REQUEST_STATUS_CHANGED,
    LEGAL_REQUEST_COMPLETED,
    LEGAL_DOCUMENT_ADDED,

    PROCUREMENT_CREATED,
    VENDOR_SELECTED,
    RFQ_CREATED,
    RFQ_SENT,
    VENDOR_QUOTATION_RECEIVED,
    VENDOR_FINALIZED,
    PURCHASE_ORDER_CREATED,
    PURCHASE_ORDER_STATUS_CHANGED,
    PAYMENT_REQUEST_CREATED,
    PAYMENT_REQUEST_STATUS_CHANGED,
    EXPENSE_CREATED,
    EXPENSE_STATUS_CHANGED,

    COMMENT_ADDED,
    NOTE_ADDED
}
